
# ==========================================
# Fonts and Icons
# ==========================================

font_family      	CaskaydiaCove Nerd Font Mono
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto
font_size        	11

# ==========================================
# Interface and Performance
# ==========================================

disable_ligatures		no
enable_audio_bell 		no
window_padding_width 	25

confirm_os_window_close 0

shell				zsh
shell_integration	disabled

cursor_shape    block
cursor_trail    1

url_style	 	curly

remember_window_size   yes
initial_window_width   640
initial_window_height  480
window_padding_width   20
#cursor_blink_interval 0.6

background_opacity 		      0.8
dynamic_background_opacity    yes
scrollbar_handle_opacity      0
scrollbar_track_opacity	 	  0
scrollbar_track_hover_opacity 0
confirm_os_window_close		  0

sync_to_monitor no

# ==========================================
# Keybinds
# ==========================================
#map ctrl+c       copy_or_interrupt

# Búsqueda (Usando los scripts .py incluidos)
#map ctrl+f       launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
#map kitty_mod+f  launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll y Zoom
#map page_up      scroll_page_up
#map page_down    scroll_page_down

#map ctrl+plus    change_font_size all +1
#map ctrl+equal   change_font_size all +1
#map ctrl+kp_add  change_font_size all +1
#map ctrl+minus   change_font_size all -1
#map ctrl+underscore change_font_size all -1
#map ctrl+kp_subtract change_font_size all -1
#map ctrl+0       change_font_size all 0
#map ctrl+kp_0    change_font_size all 0

map ctrl+shift+r load_config_file

include ~/.cache/wal/colors-kitty.conf
