#!/bin/bash
#
# Requires `jq` to parse hyprctl output (sudo pacman -S jq if you don't have it)

STATE_FILE="/tmp/hypr_macos_mode"
BACKUP_FILE="/tmp/hypr_macos_backup.json"
RULES_FILE="$HOME/.config/hypr/macos_rules.lua"
DAEMON_SCRIPT="$HOME/.config/hypr/scripts/macos_geometry_daemon.sh"
DAEMON_PID_FILE="/tmp/hypr_macos_geometry_daemon.pid"

if [ -f "$STATE_FILE" ]; then
    # --- DISABLE MACOS MODE ---
    rm "$STATE_FILE"

    # Stop the daemon that remembers window sizes
    if [ -f "$DAEMON_PID_FILE" ]; then
        kill "$(cat "$DAEMON_PID_FILE")" 2>/dev/null
        rm -f "$DAEMON_PID_FILE"
    fi

    # Empty out the rules so they don't apply to new windows
    echo "-- macOS mode inactive (auto-generated by toggle_macos.sh)" > "$RULES_FILE"

    # Restore default gaps (in the file itself, not just at runtime)
    hyprctl eval 'hl.config({ general = { gaps_out = "2, 12, 12, 12" } })'

    hyprctl reload

    # Restore the (tiled/position/size) state of the windows we had
    # set to floating
    if [ -f "$BACKUP_FILE" ]; then
        jq -c '.[]' "$BACKUP_FILE" | while read -r win; do
            addr=$(echo "$win" | jq -r '.address')
            was_floating=$(echo "$win" | jq -r '.floating')

            if [ "$was_floating" = "false" ]; then
                hyprctl dispatch "hl.dsp.window.float({ action = 'off', window = 'address:$addr' })"
            fi
        done
        rm -f "$BACKUP_FILE"
    fi

    #notify-send "Hyprland" "Tiling mode restored"
else
    # --- ENABLE MACOS MODE ---
    touch "$STATE_FILE"

    # Save the current state of open windows so it can be restored
    # when the mode is disabled
    hyprctl clients -j > "$BACKUP_FILE"

    # Start the daemon that remembers per-app sizes/positions
    nohup "$DAEMON_SCRIPT" >/tmp/hypr_macos_geometry_daemon.log 2>&1 &
    echo $! > "$DAEMON_PID_FILE"

    # Write the rule (for new windows) and the dock gap
    cat <<EOF > "$RULES_FILE"
hl.window_rule({
    name = "macos-mode-global",
    match = { class = ".*" },
    float = true,
    center = true,
    size = "1280 800",
})

hl.config({
    general = {
        gaps_out = { top = 2, right = 12, bottom = 80, left = 12 },
    },
})
EOF

    hyprctl reload

    # Also apply floating mode to windows that are ALREADY OPEN,
    # since windowrules only affect new windows
    hyprctl clients -j | jq -c '.[]' | while read -r win; do
        addr=$(echo "$win" | jq -r '.address')
        cur_w=$(echo "$win" | jq -r '.size[0]')
        cur_h=$(echo "$win" | jq -r '.size[1]')

        target_w=1280
        target_h=800
        delta_x=$((target_w - cur_w))
        delta_y=$((target_h - cur_h))

        hyprctl dispatch "hl.dsp.window.float({ action = 'on', window = 'address:$addr' })"
        hyprctl dispatch "hl.dsp.window.resize({ x = $delta_x, y = $delta_y, window = 'address:$addr' })"
        hyprctl dispatch "hl.dsp.window.center({ window = 'address:$addr' })"
    done

    #notify-send "Hyprland" "macOS mode activated"
fi