#!/usr/bin/env bash

# ============================================================
# Hyprland macOS mode toggle
#
# Tiling mode:
#   - normal Hyprland/dwindle behaviour
#
# macOS mode:
#   - normal application windows become floating
#   - new windows open centered
#   - new windows start at a sensible default size
#   - Hyprland remembers floating window sizes natively
#   - extra bottom gap leaves room for the Dock
#
# No polling and no background geometry daemon.
# ============================================================

set -u


# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

STATE_FILE="/tmp/hypr_macos_mode"
BACKUP_FILE="/tmp/hypr_macos_backup.json"

RULES_FILE="$HOME/.config/hypr/macos_rules.lua"

MAXIMIZE_STATE_DIR="/tmp/hypr_macos_maximize"


# ------------------------------------------------------------
# Default geometry for windows entering macOS mode
# ------------------------------------------------------------

DEFAULT_WIDTH=1280
DEFAULT_HEIGHT=800


# ============================================================
# Helpers
# ============================================================

dispatch() {
    hyprctl dispatch "$1" >/dev/null 2>&1
}


window_exists() {
    local addr="$1"

    hyprctl clients -j 2>/dev/null |
        jq -e \
            --arg addr "$addr" \
            '.[] | select(.address == $addr)' \
            >/dev/null 2>&1
}


# ============================================================
# Disable macOS mode
# ============================================================

disable_macos_mode() {

    rm -f "$STATE_FILE"


    # --------------------------------------------------------
    # Remove macOS rules
    # --------------------------------------------------------

    cat > "$RULES_FILE" <<'EOF'
-- macOS mode inactive
-- Auto-generated by toggle_macos.sh
EOF


    # Reloading hyprland.lua restores the normal gaps:
    #
    # gaps_out = {
    #     top = 2,
    #     right = 12,
    #     bottom = 12,
    #     left = 12
    # }
    #
    # and removes the macOS global floating rule.

    hyprctl reload >/dev/null 2>&1


    # --------------------------------------------------------
    # Restore windows that existed before macOS mode
    # --------------------------------------------------------

    if [ -f "$BACKUP_FILE" ]; then

        while IFS= read -r win; do

            addr=$(jq -r '.address // empty' <<< "$win")

            [ -z "$addr" ] && continue

            window_exists "$addr" || continue


            was_floating=$(jq -r '.floating' <<< "$win")


            # ------------------------------------------------
            # Window originally belonged to the tiling layout
            # ------------------------------------------------

            if [ "$was_floating" = "false" ]; then

                dispatch \
                    "hl.dsp.window.float({
                        action = 'off',
                        window = 'address:$addr'
                    })"

                continue
            fi


            # ------------------------------------------------
            # Window was already floating before enabling
            # macOS mode.
            #
            # Restore its original geometry.
            # ------------------------------------------------

            x=$(jq -r '.at[0]' <<< "$win")
            y=$(jq -r '.at[1]' <<< "$win")

            w=$(jq -r '.size[0]' <<< "$win")
            h=$(jq -r '.size[1]' <<< "$win")


            dispatch \
                "hl.dsp.window.resize({
                    x = $w,
                    y = $h,
                    relative = false,
                    window = 'address:$addr'
                })"


            dispatch \
                "hl.dsp.window.move({
                    x = $x,
                    y = $y,
                    relative = false,
                    window = 'address:$addr'
                })"

        done < <(jq -c '.[]' "$BACKUP_FILE" 2>/dev/null)

    fi


    # --------------------------------------------------------
    # Cleanup
    # --------------------------------------------------------

    rm -f "$BACKUP_FILE"

    rm -rf "$MAXIMIZE_STATE_DIR"


    # Optional notification
    #
    # notify-send \
    #     "Hyprland" \
    #     "Tiling mode restored"
}


# ============================================================
# Enable macOS mode
# ============================================================

enable_macos_mode() {

    # --------------------------------------------------------
    # Remember the exact state of currently open windows
    # --------------------------------------------------------

    hyprctl clients -j > "$BACKUP_FILE"


    touch "$STATE_FILE"


    # --------------------------------------------------------
    # Generate rules for windows opened while macOS mode
    # is active.
    #
    # persistent_size is implemented directly by Hyprland.
    # No external geometry daemon is necessary.
    # --------------------------------------------------------

    cat > "$RULES_FILE" <<EOF
-- ============================================================
-- macOS mode
-- Auto-generated by toggle_macos.sh
-- ============================================================


hl.window_rule({
    name = "macos-mode-global",

    match = {
        class = ".*",
    },

    float = true,
    center = true,

    size = {
        "$DEFAULT_WIDTH",
        "$DEFAULT_HEIGHT",
    },

    persistent_size = true,
})


hl.config({
    general = {

        gaps_out = {
            top = 2,
            right = 12,
            bottom = 80,
            left = 12,
        },

    },
})
EOF


    # --------------------------------------------------------
    # Load generated rules
    # --------------------------------------------------------

    hyprctl reload >/dev/null 2>&1


    # --------------------------------------------------------
    # Convert windows that were ALREADY open.
    #
    # Window rules only affect newly created windows, so
    # existing tiled windows need to be converted manually.
    # --------------------------------------------------------

    while IFS= read -r win; do

        addr=$(jq -r '.address // empty' <<< "$win")

        [ -z "$addr" ] && continue


        # ----------------------------------------------------
        # Ignore windows that disappeared during the process
        # ----------------------------------------------------

        window_exists "$addr" || continue


        # ----------------------------------------------------
        # Float
        # ----------------------------------------------------

        dispatch \
            "hl.dsp.window.float({
                action = 'on',
                window = 'address:$addr'
            })"


        # ----------------------------------------------------
        # Initial size
        # ----------------------------------------------------

        dispatch \
            "hl.dsp.window.resize({
                x = $DEFAULT_WIDTH,
                y = $DEFAULT_HEIGHT,
                relative = false,
                window = 'address:$addr'
            })"


        # ----------------------------------------------------
        # Center
        # ----------------------------------------------------

        dispatch \
            "hl.dsp.window.center({
                window = 'address:$addr'
            })"


    done < <(jq -c '.[]' "$BACKUP_FILE")


    rm -rf "$MAXIMIZE_STATE_DIR"


    # Optional notification
    #
    # notify-send \
    #     "Hyprland" \
    #     "macOS mode activated"
}


# ============================================================
# Toggle
# ============================================================

if [ -f "$STATE_FILE" ]; then
    disable_macos_mode
else
    enable_macos_mode
fi