#!/usr/bin/env bash

# ============================================================
# Hyprland macOS mode toggle
#
# Tiling mode:
#   - normal Hyprland/dwindle behaviour
#
# macOS mode:
#   - normal application windows become floating
#   - new windows open centered
#   - new windows start at a sensible default size
#   - Hyprland remembers floating window sizes natively
#   - extra bottom gap leaves room for the Dock
#
# The mode is bound to the CURRENT Hyprland instance.
# A logout/reboot/new Hyprland instance always starts in
# normal tiling mode.
#
# No polling and no background geometry daemon.
# ============================================================

set -u

STATE_FILE="/tmp/hypr_macos_mode"
BACKUP_FILE="/tmp/hypr_macos_backup.json"
RULES_FILE="$HOME/.config/hypr/macos_rules.lua"
MAXIMIZE_STATE_DIR="/tmp/hypr_macos_maximize"

DEFAULT_WIDTH=1280
DEFAULT_HEIGHT=800

CURRENT_INSTANCE="${HYPRLAND_INSTANCE_SIGNATURE:-}"


dispatch() {
    hyprctl dispatch "$1" >/dev/null 2>&1
}


window_exists() {
    local addr="$1"

    hyprctl clients -j 2>/dev/null |
        jq -e --arg addr "$addr" \
            '.[] | select(.address == $addr)' \
            >/dev/null 2>&1
}


macos_mode_active() {
    [ -n "$CURRENT_INSTANCE" ] || return 1
    [ -f "$STATE_FILE" ] || return 1

    local saved_instance
    saved_instance=$(head -n 1 "$STATE_FILE" 2>/dev/null || true)

    [ -n "$saved_instance" ] || return 1
    [ "$saved_instance" = "$CURRENT_INSTANCE" ]
}


backup_contains_window() {
    local addr="$1"

    [ -f "$BACKUP_FILE" ] || return 1

    jq -e --arg addr "$addr" \
        '.[] | select(.address == $addr)' \
        "$BACKUP_FILE" \
        >/dev/null 2>&1
}


write_inactive_rules() {
    cat > "$RULES_FILE" <<'EOF'
-- macOS mode inactive
-- Auto-generated by toggle_macos.sh
EOF
}


disable_macos_mode() {
    rm -f "$STATE_FILE"

    write_inactive_rules

    # First reload removes the macOS global rule and restores normal gaps.
    hyprctl reload >/dev/null 2>&1

    # Restore windows that already existed before enabling macOS mode.
    if [ -f "$BACKUP_FILE" ]; then
        while IFS= read -r win; do
            addr=$(jq -r '.address // empty' <<< "$win")
            [ -z "$addr" ] && continue
            window_exists "$addr" || continue

            was_floating=$(jq -r '.floating' <<< "$win")

            if [ "$was_floating" = "false" ]; then
                dispatch \
                    "hl.dsp.window.float({
                        action = 'off',
                        window = 'address:$addr'
                    })"
            else
                x=$(jq -r '.at[0]' <<< "$win")
                y=$(jq -r '.at[1]' <<< "$win")
                w=$(jq -r '.size[0]' <<< "$win")
                h=$(jq -r '.size[1]' <<< "$win")

                dispatch \
                    "hl.dsp.window.float({
                        action = 'on',
                        window = 'address:$addr'
                    })"

                dispatch \
                    "hl.dsp.window.resize({
                        x = $w,
                        y = $h,
                        relative = false,
                        window = 'address:$addr'
                    })"

                dispatch \
                    "hl.dsp.window.move({
                        x = $x,
                        y = $y,
                        relative = false,
                        window = 'address:$addr'
                    })"
            fi
        done < <(jq -c '.[]' "$BACKUP_FILE" 2>/dev/null)
    fi

    # Windows created during macOS mode are not in the backup.
    # Return them to normal tiling, except hidden/special windows.
    while IFS= read -r win; do
        addr=$(jq -r '.address // empty' <<< "$win")
        workspace=$(jq -r '.workspace.name // empty' <<< "$win")

        [ -z "$addr" ] && continue

        case "$workspace" in
            special:*)
                continue
                ;;
        esac

        if ! backup_contains_window "$addr"; then
            dispatch \
                "hl.dsp.window.float({
                    action = 'off',
                    window = 'address:$addr'
                })"
        fi
    done < <(hyprctl clients -j 2>/dev/null | jq -c '.[]')

    # Re-apply the normal configuration after state restoration.
    hyprctl reload >/dev/null 2>&1

    rm -f "$BACKUP_FILE"
    rm -rf "$MAXIMIZE_STATE_DIR"
}


enable_macos_mode() {
    if [ -z "$CURRENT_INSTANCE" ]; then
        echo "toggle_macos.sh: HYPRLAND_INSTANCE_SIGNATURE is not set" >&2
        exit 1
    fi

    # Save the current state BEFORE changing windows.
    hyprctl clients -j > "$BACKUP_FILE"

    # Persist only for this exact Hyprland instance.
    printf '%s\n' "$CURRENT_INSTANCE" > "$STATE_FILE"

    cat > "$RULES_FILE" <<EOF
-- ============================================================
-- macOS mode
-- Auto-generated by toggle_macos.sh
-- ============================================================

hl.window_rule({
    name = "macos-mode-global",

    match = {
        class = ".*",
    },

    float = true,
    center = true,

    size = {
        "$DEFAULT_WIDTH",
        "$DEFAULT_HEIGHT",
    },

    persistent_size = true,
})

hl.config({
    general = {
        gaps_out = {
            top = 2,
            right = 12,
            bottom = 80,
            left = 12,
        },
    },
})
EOF

    hyprctl reload >/dev/null 2>&1

    # Convert windows that were already open.
    while IFS= read -r win; do
        addr=$(jq -r '.address // empty' <<< "$win")
        workspace=$(jq -r '.workspace.name // empty' <<< "$win")

        [ -z "$addr" ] && continue
        window_exists "$addr" || continue

        case "$workspace" in
            special:*)
                continue
                ;;
        esac

        dispatch \
            "hl.dsp.window.float({
                action = 'on',
                window = 'address:$addr'
            })"

        dispatch \
            "hl.dsp.window.resize({
                x = $DEFAULT_WIDTH,
                y = $DEFAULT_HEIGHT,
                relative = false,
                window = 'address:$addr'
            })"

        dispatch \
            "hl.dsp.window.center({
                window = 'address:$addr'
            })"

    done < <(jq -c '.[]' "$BACKUP_FILE")

    rm -rf "$MAXIMIZE_STATE_DIR"
}


if macos_mode_active; then
    disable_macos_mode
else
    # Any old state belongs to another Hyprland instance.
    rm -f "$STATE_FILE"
    rm -f "$BACKUP_FILE"
    rm -rf "$MAXIMIZE_STATE_DIR"

    write_inactive_rules
    enable_macos_mode
fi
