-- ##################################################################
--                                                                #
--                   HYPRLAND CONFIGURATION FILE                  #
--                                                                #
-- ##################################################################

-- CONVERSION NOTE (pywal color source):
-- The original "source" pointed to a hyprlang .conf (colors-hyprland.conf)
-- generated by pywal. Since Hyprland 0.55, hyprland.lua can no longer load
-- a .conf with hyprlang variables directly: only .lua files can be
-- required/loaded. Pywal also generates an equivalent template at
-- ~/.cache/wal/colors-hyprland.lua (a table with color1, color2,
-- background, ...), so that version is loaded here instead. If your pywal
-- template doesn't generate that .lua yet, you'll need to create/enable it
-- to keep the same result.
local colors = dofile("/home/javier/.cache/wal/colors-hyprland.lua")

-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- require("myColors")

-- ########################
--- GHOST CURSOR FIX ---
-- ########################

hl.config({
    cursor = {
        no_hardware_cursors = false,
    },
})

-- ################
--- MONITORS ---
-- ################

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({ output = "eDP-1", mode = "2560x1600@60", position = "0x0", scale = 1.33 })     -- hyprctl monitors	..., scale
hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "auto-left", scale = 1 })  -- External monitor HP M24f

-- ###################
--- MY PROGRAMS ---
-- ###################

-- See https://wiki.hypr.land/Configuring/Keywords/

local terminal = "kitty"
local fileManager = "nautilus"
local browser = "firefox"
local editor = "code"

-- #################
--- AUTOSTART ---
-- #################

-- Environment variables to force dark theme in GTK apps and disable portal theming
-- hl.env("GTK_THEME", "adw-gtk3-dark")
hl.env("ADW_DISABLE_PORTAL", "1")

-- --- FORCE INTEGRATED GRAPHICS (BATTERY) ---
hl.env("AQ_DRM_DEVICES", "/dev/dri/card2:/dev/dri/card1")
hl.env("WLR_DRM_DEVICES", "/dev/dri/card2:/dev/dri/card1")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.on("hyprland.start", function ()
    -- Startup commands to ensure the system knows we prefer dark theme
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'")

    -- Startup commands to launch background services and applications
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/hypr/scripts/power_mode.sh")
    hl.exec_cmd("~/.config/quickshell/scripts/backend_daemon.sh")
    hl.exec_cmd("python3 -m compileall -q ~/.config/quickshell/scripts/")
    hl.exec_cmd("python3 ~/.config/quickshell/scripts/app_usage_daemon.py")
    hl.exec_cmd("quickshell")
    -- hl.exec_cmd("qs -c overview")
    hl.exec_cmd("qs -p ~/.config/quickshell/overview")

    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

-- #############################
--- ENVIRONMENT VARIABLES ---
-- #############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- ###################
--- PERMISSIONS ---
-- ###################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--     ecosystem = {
--         enforce_permissions = true,
--     },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-- #####################
--- LOOK AND FEEL ---
-- #####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/
-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        -- Window configuration. See https://wiki.hypr.land/Configuring/Windows/ for more
        gaps_in = 5,
        gaps_out = { top = 2, right = 12, bottom = 12, left = 12 },
        border_size = 2,

        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        col = {
            -- active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            -- inactive_border = "rgba(595959aa)",
            active_border = { colors = { colors.color1, colors.color2 }, angle = 45 },
            inactive_border = colors.background,
        },

        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity = 0.85,
        inactive_opacity = 0.75,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },

        -- https://wiki.hypr.land/Configuring/Variables/#blur

        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            vibrancy = 0.12,
        }
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true, -- yes, please :)
    },
})

-- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves

--                NAME,           X0,   Y0,   X1,   Y1
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })

-- Default animations, see https://wiki.hypr.land/Configuring/Animations/

--                   NAME,          ONOFF, SPEED, CURVE,        [STYLE]
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--
--     border_size = 0,
--     rounding = 0,
-- })
--
-- hl.window_rule({
--     name = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--
--     border_size = 0,
--     rounding = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        -- pseudotile = true, -- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        -- vfr = true,
        vrr = 1,
        disable_autoreload = false,

        -- --- Turn off Hyprland/CachyOS default wallpapers ---
        disable_hyprland_logo = true,
        force_default_wallpaper = 0,
        background_color = "rgb(000000)",
    },
})

-- #############
--- INPUT ---
-- #############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "es",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",

        numlock_by_default = true,

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
-- hl.gesture({ fingers = 3, direction = "up", action = function() hl.exec_cmd("qs ipc -c overview call overview toggle") end })
hl.gesture({ fingers = 3, direction = "up", action = function() hl.exec_cmd("qs ipc -p ~/.config/quickshell/overview call overview toggle") end })

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- ###################
--- KEYBINDINGS ---
-- ###################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

-- hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("~/.config/hypr/scripts/kitty_launch.sh"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", function()
    if os.execute("command -v hyprshutdown >/dev/null 2>&1") then
        hl.exec_cmd("hyprshutdown")
    else
        hl.dispatch(hl.dsp.exit())
    end
end)
-- hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("MOZ_ENABLE_WAYLAND=1 firefox"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("code"))
hl.bind(mainMod .. " + SPACE", hl.dsp.global("quickshell:launcher"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("~/.config/quickshell/scripts/launch.sh"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.config/quickshell/scripts/kill.sh"))
-- hl.bind("SUPER + L", hl.dsp.exec_cmd("quickshell -n -p ~/.config/quickshell/lock"))
-- hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock")) -- versión anterior (hyprlock), por si hay que revertir
-- hl.bind("SUPER + L", hl.dsp.exec_cmd("qs -p ~/.config/quickshell/lockscreen.qml"))
-- hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("SUPER + SHIFT + code:201", hl.dsp.exec_cmd("warp-terminal"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = 0 }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("~/.config/hypr/scripts/macos_maximize.sh"))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("~/.config/hypr/scripts/macos_minimize.sh"))
-- hl.bind(mainMod .. " + W", hl.dsp.global("wallpaper_menu"))
hl.bind(mainMod .. " + W", hl.dsp.global("quickshell:wallpaper_menu"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle_macos.sh"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Super + PrintScreen: Instant full-screen capture and notify the island
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("~/.config/rofi/launchers/screenshot.sh --desktop && touch /tmp/qs_shutter"))
-- Shift + Super + Print: Instant area capture and notify the island
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("~/.config/rofi/launchers/screenshot.sh --area && touch /tmp/qs_shutter"))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Open and step through the list
hl.bind("ALT + Tab", hl.dsp.exec_cmd("qs ipc -p ~/.config/quickshell call alttab next"))

-- Confirm and close on ALT release (works for both Left Alt and Right Alt)
-- NOTE: "release = true, transparent = true" is the closest translation of the
-- r (release) + t (transparent) flags from "bindrt"; double-check against the
-- hl.bind reference if your version uses different field names for these flags.
hl.bind("ALT + Alt_L", hl.dsp.exec_cmd("qs ipc -p ~/.config/quickshell call alttab commit"), { release = true, transparent = true })
hl.bind("ALT + Alt_R", hl.dsp.exec_cmd("qs ipc -p ~/.config/quickshell call alttab commit"), { release = true, transparent = true })

-- ##############################
--- WINDOWS AND WORKSPACES ---
-- ##############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },

    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name = "move-hyprland-run",

    match = { class = "hyprland-run" },

    move = "20 monitor_h-120",
    float = true,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Quickshell bar rules
-- hl.layer_rule({
--     name = "quickshell_rules",
--     match = { namespace = "^quickshell$" },
--     blur = true,
--     ignore_alpha = 0.1,
-- })

-- Rules for the wallpaper carousel
-- hl.layer_rule({
--     name = "wall_carousel_blur",
--     match = { namespace = "^wall_carousel$" },
--     blur = true,
--     ignore_alpha = 0.05,
-- })

-- Rules for Quickshell
-- hl.layer_rule({
--     name = "quickshell_blur",
--     match = { namespace = "^quickshell$" },
--     blur = true,
--     ignore_alpha = 0.05,
-- })

-- Rules for the wallpaper carousel
hl.layer_rule({ match = { namespace = "wall_carousel" }, blur = true, ignore_alpha = 0.05 })

-- Rules for Quickshell
hl.layer_rule({ match = { namespace = "quickshell" }, blur = true, ignore_alpha = 0.05 })

-- HyprMod managed settings
-- CONVERSION NOTE: "hyprland-gui.conf" is still .conf (hyprlang), and
-- hyprland.lua can't load it with "source"/require. If the tool that
-- generates it (HyprMod) doesn't produce a .lua version yet, you'll need to
-- adapt it, or load it with dofile() once it exists as .lua:
dofile("/home/javier/.config/hypr/hyprland-gui.lua")

-- macos_rules.lua IS adapted: toggle_macos.sh now generates it directly in
-- Lua syntax (hl.window_rule / hl.config) instead of macos_rules.conf.
-- Loading it here executes its calls as-is.
-- Guarded with a file-exists check so a missing file (e.g. before
-- toggle_macos.sh has been run for the first time) doesn't crash the
-- whole config.
local macos_rules_path = "/home/javier/.config/hypr/macos_rules.lua"
local macos_rules_file = io.open(macos_rules_path, "r")
if macos_rules_file then
    macos_rules_file:close()
    dofile(macos_rules_path)
end

-- Custom margins for any workspace hosted on the external monitor (HDMI-A-1)
-- gaps_out order: top, right, bottom, left
hl.workspace_rule({ workspace = "m[HDMI-A-1]", gaps_out = { top = 10, right = 10, bottom = 10, left = 10 }, gaps_in = 4 })
