general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita abrir múltiples instancias de hyprlock
    before_sleep_cmd = loginctl lock-session    # Asegura que se bloquee antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Enciende la pantalla tras despertar
}

# 0. AVISO: Bajar el brillo de la pantalla (4.5 minutos)
# Sirve como advertencia antes de bloquear y recorta consumo
listener {
    timeout = 270                               
    on-timeout = brightnessctl -s set 10%       # Guarda el brillo actual y baja al 10%
    on-resume = brightnessctl -r                # Restaura el brillo original si mueves el ratón
}

# 1. Bloquear la pantalla (5 minutos)
listener {
    timeout = 300                               
    on-timeout = loginctl lock-session          
}

# 2. Apagar la pantalla (5.5 minutos)
listener {
    timeout = 330                               
    on-timeout = hyprctl dispatch dpms off      
    on-resume = hyprctl dispatch dpms on        
}

# 3. Suspender el equipo (15 minutos)
listener {
    timeout = 900                               
    on-timeout = systemctl suspend              
}
