-- Generated by HyprMod

-- Variables de entorno
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Aplicación en Hyprland y sincronización con GTK/XWayland
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("/home/javier/.config/hypr/scripts/set_cursor.sh")
end)
